image: windows-server-2019-dc

environment:
  scripts_version: 1.0.0

clone_script:
- ps: Invoke-WebRequest "https://github.com/appveyor/build-images/archive/$($env:scripts_version).zip" -OutFile scripts.zip
- dir
- ps: Expand-Archive -Path scripts.zip -DestinationPath $env:APPVEYOR_BUILD_FOLDER -Force

build_script:
- cd build-images-%scripts_version%
- dir

test: off
