image: windows-server-2019-dc

environment:
  scripts_version: 1.0.0
  base_dir: src\build-images-%scripts_version%\scripts\Windows
  APPVEYOR_BAKE_IMAGE: bootstrap-win-test-1

init:
- ps: $ProgressPreference = 'SilentlyContinue'
- ps: $ErrorActionPreference = 'Stop'

clone_script:
- ps: Invoke-WebRequest "https://github.com/appveyor/build-images/archive/$($env:scripts_version).zip" -OutFile scripts.zip
- ps: Expand-Archive -Path $env:APPVEYOR_BUILD_FOLDER\scripts.zip -DestinationPath $env:APPVEYOR_BUILD_FOLDER\src -Force

build_script:
- cd %base_dir%
- ps: .\init_server.ps1
#- ps: .\extend_system_volume.ps1

# Restart VM
- ps: Start-Sleep -s 5
- ps: Restart-Computer
- ps: Start-Sleep -s 5

- cd %base_dir%
- ps: Copy-Item .\path-utils.psm1 "$env:TEMP\path-utils.psm1"
- ps: .\install_path_utils.ps1

test: off
