image: windows-server-2019-dc

environment:
  scripts_version: 1.0.0
  base_dir: src\build-images-%scripts_version%\scripts\Windows
  APPVEYOR_BAKE_IMAGE: bootstrap-win-test-1

init:
- ps: $ProgressPreference = 'SilentlyContinue'
- ps: $ErrorActionPreference = 'Stop'

clone_script:
- ps: Invoke-WebRequest "https://github.com/appveyor/build-images/archive/$($env:scripts_version).zip" -OutFile scripts.zip
- ps: Expand-Archive -Path $env:APPVEYOR_BUILD_FOLDER\scripts.zip -DestinationPath $env:APPVEYOR_BUILD_FOLDER\src -Force

build_script:
- cd %base_dir%
- ps: .\init_server.ps1
#- ps: .\extend_system_volume.ps1

# Restart VM
- ps: Start-Sleep -s 5
- ps: Restart-Computer
- ps: Start-Sleep -s 5

- cd %base_dir%
- ps: Copy-Item .\path-utils.psm1 "$env:TEMP\path-utils.psm1"
- ps: .\install_powershell_core.ps1
- ps: .\install_powershell_get.ps1
- ps: .\install_7zip.ps1
- ps: .\install_chocolatey.ps1
- ps: .\install_webpi.ps1
- ps: .\install_nuget.ps1
- ps: .\install_pstools.ps1

- ps: .\install_git.ps1
- ps: .\install_git_lfs.ps1
- ps: .\install_mercurial.ps1
- ps: .\install_subversion.ps1
- ps: .\add_ssh_known_hosts.ps1

- ps: .\install_docker_hyperv_wsl_features.ps1

# Restart VM
- ps: Start-Sleep -s 5
- ps: Restart-Computer
- ps: Start-Sleep -s 5

#- ps: Copy-Item .\docker-appveyor.psm1 "$env:TEMP\docker-appveyor.psm1"
- ps: .\install_docker.ps1

# Restart VM
- ps: Start-Sleep -s 5
- ps: Restart-Computer
- ps: Start-Sleep -s 5

- ps: .\install_docker_after_reboot.ps1

test: off
