image: windows-server-2019-dc

environment:
  scripts_version: 1.0.0

clone_script:
- ps: Invoke-WebRequest "https://github.com/appveyor/build-images/archive/$($env:scripts_version).zip" -OutFile scripts.zip
- ps: Expand-Archive -Path scripts.zip -DestinationPath .\src -Force | Out-Null

build_script:
- cd src\build-images-%scripts_version%
- dir

test: off
