image: windows-server-2019-dc

environment:
  scripts_version: 1.0.0

init:
- ps: $ProgressPreference = 'SilentlyContinue'
- ps: $ErrorActionPreference = 'Stop'

clone_script:
- ps: Invoke-WebRequest "https://github.com/appveyor/build-images/archive/$($env:scripts_version).zip" -OutFile scripts.zip
#- ps: Expand-Archive -Path $env:APPVEYOR_BUILD_FOLDER\scripts.zip -DestinationPath $env:APPVEYOR_BUILD_FOLDER\src -Force
- ps: Add-Type -AssemblyName System.IO.Compression.FileSystem
- ps: [System.IO.Compression.ZipFile]::ExtractToDirectory($env:APPVEYOR_BUILD_FOLDER\scripts.zip, $env:APPVEYOR_BUILD_FOLDER\src)

build_script:
- cd src\build-images-%scripts_version%
- ps: .\scripts\Windows\init_server.ps1
#- ps: .\scripts\Windows\extend_system_volume.ps1
- ps: Copy-Item .\scripts\Windows\path-utils.ps1 "$env:TEMP\path-utils.psm1"
- ps: .\scripts\Windows\install_path_utils.ps1

test: off
